spring:
  datasource:
     driver-class-name : com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/article_url?useUnicode=true&characterEncoding=utf-8
     username: root
     password: root
  data:
     mongodb:
        uri : mongodb://spider:spider2018@172.30.157.88:27017/article

mybatis:
  mapper-locations: classpath:mapper/*.xml

